export const GET_CARTS = "GET_CARTS"
export const ADD_CARTS = "ADD_CARTS"
export const DELETE_CARTS = "DELETE_CARTS"
export const SAGA_GET = "SAGA_GET"
export const SAGA_POST = "SAGA_POST"
export const SAGA_DELETE = "SAGA_DELETE"
export const SET_CARTS = "SET_CARTS"